resources:
- name: source
  type: git
  source:
    branch: master
    uri: https://github.com/Nordstrom/docker-kube-deployer.git

jobs:
- name: build-image
  plan:
  - get: source
    trigger: true
  - task: build-assets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang }
      inputs:
      - name: source
        path: source
      outputs:
      - name: build
        path: build
      run:
        path: bash
        args:
          - -exc
          - |
            whoami
            env
            go version
            find .
            cd source
            make build_dir=../build
